### PR TITLE
Add timestamp.

### PR DESCRIPTION
**Pull request by tobie**
Adds an auto-generated timestamp so it's obvious when the report has last been updated.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@tobie stupid and somewhat unrelated question, but what is generating the time stamp? Is there documentation for this magic?

**Comment by tobie** [comment]
@marcoscaceres there's actually pretty good documentation on this topic. GitHub Pages [uses Jekyll](https://help.github.com/articles/using-jekyll-with-pages/), an open-source static site generator which has extensive documentation on its [own website](http://jekyllrb.com/). That's where you'll find the [complete list of available variables](http://jekyllrb.com/docs/variables/) of which `site.time` is one.

**Comment by marcoscaceres** [comment]
Thanks @tobie!

**Comment by tobie** [comment]
Cheers.

**Comment by tobie** [comment]
ping?

**Pull request merged**
